# docs info
site_name: Portfolio - Jiajie
site_url: https://jz263.github.io/mkdocs-demo/

# repo
repo_name: jz263/mkdocs-demo
repo_url: https://github.com/jz263/mkdocs-demo
edit_uri: ""

# theme
theme:
  name: material
  language: zh
  highlightjs: true

# page tree
nav:
  - Home: index.md
